-- Boundary-file names (data/geo/sacramento-neighborhoods.geojson, NAME) keyed by MapKey.For, with the
-- Neighborhood.Normalize slug. Add a row here when the source starts using a new spelling.
SET NOCOUNT ON;

DECLARE @seed TABLE (alias_key varchar(100) NOT NULL PRIMARY KEY, neighborhood nvarchar(100) NOT NULL, neighborhood_slug varchar(100) NOT NULL);

INSERT INTO @seed (alias_key, neighborhood, neighborhood_slug) VALUES
    ('airport', N'Airport', 'airport'),
    ('alhambratriangle', N'Alhambra Triangle', 'alhambra-triangle'),
    ('alkaliflat', N'Alkali Flat', 'alkali-flat'),
    ('americanriverparkway', N'American River Parkway', 'american-river-parkway'),
    ('ardenfair', N'Arden Fair', 'arden-fair'),
    ('avondale', N'Avondale', 'avondale'),
    ('belvedere', N'Belvedere', 'belvedere'),
    ('benali', N'Ben Ali', 'ben-ali'),
    ('boulevardpark', N'Boulevard Park', 'boulevard-park'),
    ('brentwood', N'Brentwood', 'brentwood'),
    ('csus', N'CSUS', 'csus'),
    ('calexpo', N'Cal Expo', 'cal-expo'),
    ('campuscommons', N'Campus Commons', 'campus-commons'),
    ('cannonindustrialpark', N'Cannon Industrial Park', 'cannon-industrial-park'),
    ('carletontract', N'Carleton Tract', 'carleton-tract'),
    ('centraloakpark', N'Central Oak Park', 'central-oak-park'),
    ('collegetown', N'College Town', 'college-town'),
    ('collegeglen', N'College/Glen', 'college-glen'),
    ('colonialheights', N'Colonial Heights', 'colonial-heights'),
    ('colonialmanor', N'Colonial Manor', 'colonial-manor'),
    ('colonialvillage', N'Colonial Village', 'colonial-village'),
    ('creekside', N'Creekside', 'creekside'),
    ('curtispark', N'Curtis Park', 'curtis-park'),
    ('delpasoheights', N'Del Paso Heights', 'del-paso-heights'),
    ('delpasopark', N'Del Paso Park', 'del-paso-park'),
    ('depotpark', N'Depot Park', 'depot-park'),
    ('dosriostriangle', N'Dos Rios Triangle', 'dos-rios-triangle'),
    ('downtown', N'Downtown', 'downtown'),
    ('eastdelpasoheights', N'East Del Paso Heights', 'east-del-paso-heights'),
    ('eastsacramento', N'East Sacramento', 'east-sacramento'),
    ('eldercreek', N'Elder Creek', 'elder-creek'),
    ('elmhurst', N'Elmhurst', 'elmhurst'),
    ('eriksonindustrialpark', N'Erikson Industrial Park', 'erikson-industrial-park'),
    ('fairgrounds', N'Fairgrounds', 'fairgrounds'),
    ('florinfruitridgeindustrialpark', N'Florin Fruitridge Industrial Park', 'florin-fruitridge-industrial-park'),
    ('freeportmanor', N'Freeport Manor', 'freeport-manor'),
    ('fruitridgemanor', N'Fruitridge Manor', 'fruitridge-manor'),
    ('gardenland', N'Gardenland', 'gardenland'),
    ('gatewaycenter', N'Gateway Center', 'gateway-center'),
    ('gatewaywest', N'Gateway West', 'gateway-west'),
    ('glenelder', N'Glen Elder', 'glen-elder'),
    ('glenwoodmeadows', N'Glenwood Meadows', 'glenwood-meadows'),
    ('golfcourseterrace', N'Golf Course Terrace', 'golf-course-terrace'),
    ('graniteregionalpark', N'Granite Regional Park', 'granite-regional-park'),
    ('greenbriar', N'Greenbriar', 'greenbriar'),
    ('greenhaven', N'Greenhaven', 'greenhaven'),
    ('hagginwood', N'Hagginwood', 'hagginwood'),
    ('hansenparkgolfcoursesite', N'Hansen Park Golf Course Site', 'hansen-park-golf-course-site'),
    ('heritagepark', N'Heritage Park', 'heritage-park'),
    ('hollywoodpark', N'Hollywood Park', 'hollywood-park'),
    ('johnsonbusinesspark', N'Johnson Business Park', 'johnson-business-park'),
    ('johnsonheights', N'Johnson Heights', 'johnson-heights'),
    ('landpark', N'Land Park', 'land-park'),
    ('lawrencepark', N'Lawrence Park', 'lawrence-park'),
    ('littlepocket', N'Little Pocket', 'little-pocket'),
    ('manganpark', N'Mangan Park', 'mangan-park'),
    ('mansionflats', N'Mansion Flats', 'mansion-flats'),
    ('marshallschool', N'Marshall School', 'marshall-school'),
    ('meadowview', N'Meadowview', 'meadowview'),
    ('medcenter', N'Med Center', 'med-center'),
    ('metrocenter', N'Metro Center', 'metro-center'),
    ('midtownwinnparkcapitalavenue', N'Midtown / Winn Park / Capital Avenue', 'midtown-winn-park-capital-avenue'),
    ('morrisoncreek', N'Morrison Creek', 'morrison-creek'),
    ('natomascorporatecenter', N'Natomas Corporate Center', 'natomas-corporate-center'),
    ('natomascreek', N'Natomas Creek', 'natomas-creek'),
    ('natomascrossing', N'Natomas Crossing', 'natomas-crossing'),
    ('natomaspark', N'Natomas Park', 'natomas-park'),
    ('newbrighton', N'New Brighton', 'new-brighton'),
    ('newerapark', N'New Era Park', 'new-era-park'),
    ('newtonbooth', N'Newton Booth', 'newton-booth'),
    ('noralto', N'Noralto', 'noralto'),
    ('northcityfarms', N'North City Farms', 'north-city-farms'),
    ('northoakpark', N'North Oak Park', 'north-oak-park'),
    ('northgate', N'Northgate', 'northgate'),
    ('northpointe', N'Northpointe', 'northpointe'),
    ('norwoodi80', N'Norwood I-80', 'norwood-i-80'),
    ('norwoodtech', N'Norwood Tech', 'norwood-tech'),
    ('oakknoll', N'Oak Knoll', 'oak-knoll'),
    ('oldnorthsacramento', N'Old North Sacramento', 'old-north-sacramento'),
    ('oldsacramento', N'Old Sacramento', 'old-sacramento'),
    ('parkerhomes', N'Parker Homes', 'parker-homes'),
    ('parkway', N'Parkway', 'parkway'),
    ('pellmainindustrialpark', N'Pell/Main Industrial Park', 'pell-main-industrial-park'),
    ('pocket', N'Pocket', 'pocket'),
    ('pointwest', N'Point West', 'point-west'),
    ('powerridge', N'Power Ridge', 'power-ridge'),
    ('rpsportscomplex', N'RP - Sports Complex', 'rp-sports-complex'),
    ('raleyindustrialpark', N'Raley Industrial Park', 'raley-industrial-park'),
    ('ramonavillage', N'Ramona Village', 'ramona-village'),
    ('regencypark', N'Regency Park', 'regency-park'),
    ('richardsonvillage', N'Richardson Village', 'richardson-village'),
    ('richmondgrove', N'Richmond Grove', 'richmond-grove'),
    ('rivergardens', N'River Gardens', 'river-gardens'),
    ('riverpark', N'River Park', 'river-park'),
    ('robla', N'Robla', 'robla'),
    ('scc', N'SCC', 'scc'),
    ('sierraoaks', N'Sierra Oaks', 'sierra-oaks'),
    ('southcityfarms', N'South City Farms', 'south-city-farms'),
    ('southhagginwood', N'South Hagginwood', 'south-hagginwood'),
    ('southlandpark', N'South Land Park', 'south-land-park'),
    ('southnatomas', N'South Natomas', 'south-natomas'),
    ('southoakpark', N'South Oak Park', 'south-oak-park'),
    ('southeastvillage', N'Southeast Village', 'southeast-village'),
    ('southernpacificrichards', N'Southern Pacific / Richards', 'southern-pacific-richards'),
    ('southsidepark', N'Southside Park', 'southside-park'),
    ('strawberrymanor', N'Strawberry Manor', 'strawberry-manor'),
    ('sundancelake', N'Sundance Lake', 'sundance-lake'),
    ('swanstonestates', N'Swanston Estates', 'swanston-estates'),
    ('tahoepark', N'Tahoe Park', 'tahoe-park'),
    ('tahoeparkeast', N'Tahoe Park East', 'tahoe-park-east'),
    ('tahoeparksouth', N'Tahoe Park South', 'tahoe-park-south'),
    ('tallacvillage', N'Tallac Village', 'tallac-village'),
    ('upperlandpark', N'Upper Land Park', 'upper-land-park'),
    ('valleyhinorthlaguna', N'Valley Hi / North Laguna', 'valley-hi-north-laguna'),
    ('valleyviewacres', N'Valleyview Acres', 'valleyview-acres'),
    ('village12', N'Village 12', 'village-12'),
    ('village14', N'Village 14', 'village-14'),
    ('village5', N'Village 5', 'village-5'),
    ('village7', N'Village 7', 'village-7'),
    ('villagegreen', N'Village Green', 'village-green'),
    ('westdelpasoheights', N'West Del Paso Heights', 'west-del-paso-heights'),
    ('westtahoepark', N'West Tahoe Park', 'west-tahoe-park'),
    ('westlake', N'Westlake', 'westlake'),
    ('willowcreek', N'Willowcreek', 'willowcreek'),
    ('willsacres', N'Wills Acres', 'wills-acres'),
    ('woodbine', N'Woodbine', 'woodbine'),
    ('woodlake', N'Woodlake', 'woodlake'),
    ('youngsheights', N'Youngs Heights', 'youngs-heights'),
    ('zbergpark', N'Z''berg Park', 'zberg-park');

UPDATE t
SET t.neighborhood = s.neighborhood, t.neighborhood_slug = s.neighborhood_slug
FROM ref.neighborhood_alias AS t
JOIN @seed AS s ON s.alias_key = t.alias_key
WHERE t.neighborhood <> s.neighborhood OR t.neighborhood_slug <> s.neighborhood_slug;

INSERT INTO ref.neighborhood_alias (alias_key, neighborhood, neighborhood_slug)
SELECT s.alias_key, s.neighborhood, s.neighborhood_slug
FROM @seed AS s
WHERE NOT EXISTS (SELECT 1 FROM ref.neighborhood_alias AS t WHERE t.alias_key = s.alias_key);
